<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“Type data dan variable”**

**Disusun Oleh :**

**Habib Alhakim**

**2611531018**

**Dosen Pengampu:**

**Dr. Ir WAHYUDI, ST., MT.**

**Asisten Praktikum:**

**Muhammad Galid Alvero**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji dan syukur penulis panjatkan ke hadirat Tuhan Yang Maha Esa atas rahmat dan karunia-Nya, sehingga penulis dapat menyelesaikan laporan praktikum Algoritma dan Pemrograman/Dasar Pemrograman ini tepat pada waktunya.

Laporan ini disusun untuk memenuhi tugas praktikum Pekan 2 mengenai penggunaan variabel, tipe data dasar (Boolean, Numerik, String), konstanta, serta operasi masukan (input) dan keluaran (output) pada bahasa pemrograman Python. Dalam penyusunannya, penulis mendapat bimbingan dan bantuan dari berbagai pihak. Oleh karena itu, penulis menyampaikan terima kasih kepada dosen pengampu mata kuliah serta para asisten laboratorium yang telah memberikan bimbingan dan arahan selama pelaksanaan praktikum.

Penulis menyadari bahwa laporan ini masih memiliki kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi penyempurnaan laporan di masa mendatang. Semoga laporan ini dapat memberikan manfaat bagi pembaca.

Padang, 2026

Habib Alhakim

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Bahasa pemrograman Python merupakan salah satu bahasa pemrograman populer yang banyak digunakan dalam pengembangan perangkat lunak, analisis data, hingga kecerdasan buatan. Keunggulan utama Python terletak pada sintaksisnya yang sederhana, bersih, dan mudah dipahami, sehingga sangat cocok digunakan oleh pemula untuk mempelajari konsep dasar pemrograman.

Dalam pemrograman, pemahaman terhadap tipe data, variabel, konstanta, serta interaksi masukan (input) dan keluaran (output) merupakan pondasi paling mendasar. Pemroses data membutuhkan deklarasi variabel yang tepat untuk menyimpan nilai sementara di dalam memori. Selain itu, penggunaan tipe data yang sesuai seperti numerik (int, float, complex), ekspresi logika (Boolean), maupun teks (String) sangat menentukan kebenaran logis dan efisiensi dari suatu program. Oleh karena itu, praktikum Pekan 2 ini dilaksanakan untuk memberikan pemahaman langsung (hands-on) mengenai implementasi konsep-konsep dasar tersebut menggunakan Python di lingkungan Visual Studio Code.

## 1.2 Tujuan
1. Memahami cara pembuatan variabel dengan penamaan berformat NIM.
2. Mengimplementasikan tipe data numerik, Boolean, dan String pada Python.
3. Menggunakan nilai tetap (constant) dengan modul typing.Final.
4. Mengolah input dari pengguna dan menampilkan output terformat.

## 1.3 Manfaat
1. Praktikan mampu menulis kode Python sesuai aturan sintaksis dasar.
2. Praktikan dapat mengolah data numerik, teks, dan logika secara benar.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori
BAB II DASAR TEORI

1. Variabel: Tempat menyimpan data di memori yang dibuat dengan operator penugasan (=). Penamaannya peka huruf besar/kecil (case-sensitive) dan tidak boleh menggunakan kata kunci bawaan Python.
2. Tipe Data Numerik: Terdiri dari int (bilangan bulat), float (bilangan desimal), dan complex (bilangan kompleks) untuk mengolah data angka.
3. Tipe Data Boolean: Tipe data bernilai True atau False yang digunakan dalam evaluasi kondisi dan logika program.
4. Tipe Data String: Teks atau sekumpulan karakter yang diapit tanda petik. Tanda petik tiga ("""...""") digunakan untuk teks multibariss.
5. Konstanta (typing.Final): Nilai tetap yang dideklarasikan menggunakan Final dari modul typing agar variabel tidak diubah nilainya.
6. Input dan Output: Fungsi input() digunakan untuk menerima masukan teks dari pengguna (perlu type casting seperti int() atau float() untuk dihitung), sedangkan print() digunakan untuk menampilkan hasil ke konsol.

## 2.2 Kode Program

### 2.2.1 Boolean_2611531018

In [5]:
#Buat file baru dengan nama Boolean_NIM.py
#nama variabel ditambah 4 digit nim terakhir contoh: nilai_5500
# Deklarasikan variabel dengan tipe data Boolean
is_lulus_1018 = True
is_cumlaude_1018 = True

# Menggunakan Boolean
nilai_1018 = 85
batas_lulus_1018 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_1018 = nilai_1018 >= batas_lulus_1018 #Hasilnya akan True

print("=== Check Kelulusan ===")
print("Nilai:", nilai_1018)
print("Apakah lulus?:", status_kelulusan_1018)
if is_lulus_1018 and is_cumlaude_1018:
    print("Selamat, Anda lulus dengan predikat Cum Laude!")

=== Check Kelulusan ===
Nilai: 85
Apakah lulus?: True
Selamat, Anda lulus dengan predikat Cum Laude!


**Penjelasan :**
1. Bagian pertama kode ini berfungsi untuk mendeklarasikan variabel is_lulus_1018 dan is_cumlaude_1018 dengan nilai awal bertipe Boolean (True), yang menandakan status awal kelulusan dan predikat cumlaude.
2. Bagian kedua berfungsi untuk menentukan nilai variabel numerik nilai_1018 (85) dan batas_lulus_1018 (75) sebagai acuan untuk mengevaluasi kondisi.
3. Bagian ketiga berfungsi untuk melakukan evaluasi kondisi menggunakan operator perbandingan (>), di mana hasil perbandingan antara nilai_1018 dan batas_lulus_1018 disimpan ke variabel status_kelulusan_1018 (bernilai True), lalu menampilkan status tersebut serta memeriksa kombinasi syarat lulus dan cumlaude menggunakan operator logika and untuk mencetak pesan ucapan selamat ke konsol.

### 2.2.2 Input_2611531018

In [3]:
# Buat file baru dengan nama Input_2611531018.py
# Buat program untuk menghitung luas persegi panjang
# Nama variabel ditambah 4 digit nim terakhir contoh: panjang_1234
# Program ini menggunakan fungsi input() untuk meminta pengguna
# memasukkan nilai panjang dan lebar persegi panjang.
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_1018 = input('Masukkan nilai panjang: ')
lebar_1018 = input('Masukkan nilai lebar: ')
luas_1018 = int(panjang_1018) * int(lebar_1018)
print("Luas =", luas_1018)

Luas = 50


**Penjelasan :**

1. Bagian pertama kode ini berfungsi untuk mengambil masukan (input) dari pengguna berupa nilai panjang dan lebar persegi panjang menggunakan fungsi input() yang disimpan dalam variabel panjang_1018 dan lebar_1018.
2. Bagian kedua berfungsi untuk menghitung luas persegi panjang dengan mengonversi (type casting) nilai panjang_1018 dan lebar_1018 dari tipe data String menjadi Integer (int()), lalu mengalikannya dan menyimpan hasilnya ke variabel luas_1018.
3. Bagian ketiga berfungsi untuk menampilkan hasil perhitungan luas persegi panjang ke konsol menggunakan fungsi print().

### 2.2.3 Konstanta_2611531018

In [4]:
# Buat file baru dengan nama Konstanta_NIM.py"
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variabel ditambah 4 digit nim terakhir contoh: jari_1234

from typing import Final
PI_1018: Final = 3.14
print("pi: %f" % (PI_1018))
jari_1018 = float(input('Masukkan nilai jari-jari: '))
luas_1018 = PI_1018 * jari_1018 * jari_1018
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_1018, luas_1018))

pi: 3.140000
Luas lingkaran dengan jari-jari 5.00 adalah 78.50


**Penjelasan :**

1. Bagian pertama kode ini berfungsi untuk mengimpor penanda tipe Final dari modul typing dan mendefinisikan konstanta PI_1018 sebesar 3.14 sebagai nilai tetap untuk perhitungan matematika.2. 2. Bagian kedua berfungsi untuk mengambil masukan pengguna berupa nilai jari-jari lingkaran menggunakan input(), lalu mengonversinya menjadi tipe data float (float()) dan menyimpannya dalam variabel jari_1018.
3. Bagian ketiga berfungsi untuk menghitung luas lingkaran berdasarkan rumus $PI \times r^2$ (PI_1018 * jari_1018 * jari_1018), lalu menampilkan nilai PI_1018 serta hasil luas lingkaran dengan format desimal dua angka di belakang koma (%.2f) ke konsol.

### 2.2.4 Numerik_2611531018

In [6]:
# Buat file dengan nama Numerik_NIM.py
# nama variabel ditambah 4 digit terakhir NIM contoh: a_5500
#create a variable with numeric type value.
a_1018=100
print("The type of variable having value", a_1018, " is ", type(a_1018))

#create a variable with float value.
b_1018=10.2345
print("The type of variable having value", b_1018, " is ", type(b_1018))

#create a variable with complex value.
c_1018=100+3j
print("The type of variable having value", c_1018, " is ", type(c_1018))

The type of variable having value 100  is  <class 'int'>
The type of variable having value 10.2345  is  <class 'float'>
The type of variable having value (100+3j)  is  <class 'complex'>


**Penjelasan :**

1. Bagian pertama kode ini berfungsi untuk mendefinisikan variabel a_1018 dengan nilai $100$ bertipe Integer (int), lalu mencetak tipe datanya ke konsol.
2. Bagian kedua berfungsi untuk mendefinisikan variabel b_1018 dengan nilai $10.2345$ bertipe Float (desimal), lalu menampilkan tipe data dari variabel tersebut.
3. Bagian ketiga berfungsi untuk mendefinisikan variabel c_1018 dengan nilai $100 + 3j$ bertipe Complex (bilangan kompleks), lalu mencetak tipe datanya ke konsol.

### 2.2.4 Numerik_2611531018

In [ ]:
# Buat file dengan nama String_NIM.py
#nama variabel ditambah 4 digit nim terakhir contoh: nama_1234
#ganti programnya dan data masing-masing
nama_1018 = "Habib"
jenis_kelamin_1018 = 'L'
alamat_1018 = """
nagari Taluak IV Suku
kec.Banuhampu
kabupaten Agam
"""
agama_1018 = "Islam"
print("Nama saya adalah " , nama_1018)
print("Jenis kelamin saya adalah " , jenis_kelamin_1018)
print("Alamat saya adalah " , alamat_1018)
print("Agama saya adalah " , agama_1018)

**Penjelasan :**

1. Bagian pertama kode ini berfungsi untuk mendefinisikan variabel string nama_1018, jenis_kelamin_1018, dan agama_1018 dengan nilai karakter tunggal atau teks pendek.
2. Bagian kedua berfungsi untuk mendefinisikan variabel alamat_1018 menggunakan multiline string (tanda petik tiga """) untuk menyimpan teks alamat yang terdiri dari beberapa baris.
3. Bagian ketiga berfungsi untuk menampilkan seluruh data identitas tersebut ke konsol menggunakan fungsi print() dengan menggabungkan string dan nilai variabel menggunakan pemisah koma.

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum yang telah dilakukan, dapat disimpulkan bahwa pemahaman mengenai variabel, tipe data dasar (Numerik, Boolean, String), konstanta, serta interaksi masukan dan keluaran (input/output) merupakan fondasi utama dalam membangun program Python yang terstruktur. Praktik penggunaan variabel dengan penamaan berformat NIM membantu menjaga identifikasi data tetap konsisten, sementara konversi tipe data (type casting) terbukti krusial saat mengolah masukan pengguna agar operasi matematika maupun logika dapat berjalan dengan benar.

Dalam konteks pemrograman Python, konsep ini memanfaatkan keunggulan sintaksis yang sederhana dan dinamis sehingga penulisan kode menjadi lebih efisien, fleksibel, serta mudah dipahami dalam mengolah berbagai jenis data.

---
## DAFTAR PUSTAKA

[1] Python Software Foundation, "Python 3 Documentation: Data Types and Variables," Python.org, 2026. [Online]. Tersedia: https://docs.python.org/3/tutorial/introduction.html [Diakses 12 September 2026].

[2] R. Rosid, "Diktat Praktikum Algoritma dan Pemrograman: Tipe Data, Variabel, dan Input/Output Python," Laboratorium Komputer, 2024, Hal. 15-22.